/**
 * TempApi
 * This is a sample openApi document
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: lampralexandros@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.TempApi);
  }
}(this, function(expect, TempApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new TempApi.Project();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Project', function() {
    it('should create an instance of Project', function() {
      // uncomment below and update the code to test Project
      //var instane = new TempApi.Project();
      //expect(instance).to.be.a(TempApi.Project);
    });

    it('should have the property id (base name: "_id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new TempApi.Project();
      //expect(instance).to.be();
    });

    it('should have the property projectName (base name: "projectName")', function() {
      // uncomment below and update the code to test the property projectName
      //var instance = new TempApi.Project();
      //expect(instance).to.be();
    });

    it('should have the property projectDescription (base name: "projectDescription")', function() {
      // uncomment below and update the code to test the property projectDescription
      //var instance = new TempApi.Project();
      //expect(instance).to.be();
    });

    it('should have the property serviceProviderName (base name: "serviceProviderName")', function() {
      // uncomment below and update the code to test the property serviceProviderName
      //var instance = new TempApi.Project();
      //expect(instance).to.be();
    });

    it('should have the property directorName (base name: "directorName")', function() {
      // uncomment below and update the code to test the property directorName
      //var instance = new TempApi.Project();
      //expect(instance).to.be();
    });

    it('should have the property countryRegistration (base name: "countryRegistration")', function() {
      // uncomment below and update the code to test the property countryRegistration
      //var instance = new TempApi.Project();
      //expect(instance).to.be();
    });

    it('should have the property companyNumber (base name: "companyNumber")', function() {
      // uncomment below and update the code to test the property companyNumber
      //var instance = new TempApi.Project();
      //expect(instance).to.be();
    });

    it('should have the property registeredOfficeAddress (base name: "registeredOfficeAddress")', function() {
      // uncomment below and update the code to test the property registeredOfficeAddress
      //var instance = new TempApi.Project();
      //expect(instance).to.be();
    });

    it('should have the property registeredOfficePostcode (base name: "registeredOfficePostcode")', function() {
      // uncomment below and update the code to test the property registeredOfficePostcode
      //var instance = new TempApi.Project();
      //expect(instance).to.be();
    });

    it('should have the property registeredOfficeCity (base name: "registeredOfficeCity")', function() {
      // uncomment below and update the code to test the property registeredOfficeCity
      //var instance = new TempApi.Project();
      //expect(instance).to.be();
    });

    it('should have the property outputType (base name: "outputType")', function() {
      // uncomment below and update the code to test the property outputType
      //var instance = new TempApi.Project();
      //expect(instance).to.be();
    });

    it('should have the property currency (base name: "currency")', function() {
      // uncomment below and update the code to test the property currency
      //var instance = new TempApi.Project();
      //expect(instance).to.be();
    });

  });

}));
